
# Generated by /home/uber/dotfiles/.vim/scripts/dependencies/cmake-3.2.3/bootstrap
# Default cmake settings.  These may be overridden any settings below.
set (CMAKE_INSTALL_PREFIX "/usr" CACHE PATH "Install path prefix, prepended onto install directories." FORCE)
set (CMAKE_DOC_DIR "/share/doc/cmake-3.2.3" CACHE PATH "Install location for documentation (relative to prefix)." FORCE)
set (CMAKE_MAN_DIR "/share/man" CACHE PATH "Install location for man pages (relative to prefix)." FORCE)
set (CMAKE_DATA_DIR "" CACHE PATH "Install location for data (relative to prefix)." FORCE)

